[build]
  # 빌드 명령어 (없음)
  command = ""
  # 배포할 디렉토리
  publish = "public"
  # Functions 디렉토리
  functions = "netlify/functions"

# 리다이렉트 설정
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
